apiVersion: v1
kind: Service
metadata:
  name: budget-analyzer-web
  namespace: default
  labels:
    app: budget-analyzer-web
spec:
  type: ClusterIP
  selector:
    app: budget-analyzer-web
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
