apiVersion: v1
kind: Service
metadata:
  name: session-gateway
  namespace: default
  labels:
    app: session-gateway
spec:
  type: ClusterIP
  selector:
    app: session-gateway
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
