apiVersion: v1
kind: Service
metadata:
  name: currency-service
  namespace: default
  labels:
    app: currency-service
spec:
  type: ClusterIP
  selector:
    app: currency-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
